Client script template
Both client and server scripts work well

diff --git a/nvflare/lighter/impl/master_template.yml b/nvflare/lighter/impl/master_template.yml
--- a/nvflare/lighter/impl/master_template.yml
+++ b/nvflare/lighter/impl/master_template.yml
@@ -375,13 +375,74 @@ start_ovsr_sh: |
 start_cln_sh: |
   #!/usr/bin/env bash
   DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
-  $DIR/sub_start.sh &
+  all_arguments="${@}"
+  doCloud=false
+  # parse arguments
+  while [[ $# -gt 0 ]]
+  do
+      key="$1"
+      case $key in
+        --cloud)
+          doCloud=true
+          csp=$2
+          shift
+        ;;
+      esac
+      shift
+  done
+
+  if [ $doCloud = true ]
+  then
+    case $csp in
+      azure)
+        $DIR/azure_start.sh ${all_arguments}
+        ;;
+      *)
+        echo "Only on-prem or Azure is currently supported."
+    esac
+  else
+    $DIR/sub_start.sh &
+  fi
 
 start_svr_sh: |
   #!/usr/bin/env bash
   DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
-  $DIR/sub_start.sh &
+  all_arguments="${@}"
+  doCloud=false
+  ha_mode={~~ha_mode~~}
+  # parse arguments
+  while [[ $# -gt 0 ]]
+  do
+    key="$1"
+    case $key in
+      --cloud)
+        if [ $ha_mode = false ]
+        then
+          doCloud=true
+          csp=$2
+          shift
+        else
+          echo "Cloud launch does not support NVFlare HA mode."
+          exit 1
+        fi
+      ;;
+    esac
+    shift
+  done
 
+  if [ $doCloud = true ]
+  then
+    case $csp in
+      azure)
+        $DIR/azure_start.sh ${all_arguments}
+        ;;
+      *)
+        echo "Only on-prem or Azure is currently supported."
+    esac
+  else
+    $DIR/sub_start.sh &
+  fi
+    
 stop_fl_sh: |
   #!/usr/bin/env bash
   DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
@@ -819,3 +880,553 @@ helm_chart_values: |
   persist: /home/nvflare
 
 
+azure_start_svr_sh: |
+  #!/usr/bin/env bash
+  
+  DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
+  function report_status() {
+    status="$1"
+    if [ "${status}" -ne 0 ]
+    then
+      echo "$2 failed"
+      exit "${status}"
+    fi
+  }
+
+  function check_binary() {
+    echo -n "Checking if $1 exists. => "
+    if ! command -v $1 &> /dev/null
+    then
+      echo "not found. $2"
+      exit 1
+    else
+      echo "found"
+    fi
+  }
+
+  function prompt() {
+    local __default="$1"
+    read -p "$2" ans
+    if [[ ! -z "$ans" ]]
+    then
+      eval $__default="'$ans'"
+    fi
+  }
+
+  # parse arguments
+  while [[ $# -gt 0 ]]
+  do
+    key="$1"
+    case $key in
+      --config)
+        config_file=$2
+        shift
+      ;;
+    esac
+    shift
+  done
+  
+  RESOURCE_GROUP=nvflare_rg
+  VM_NAME=nvflare_server
+  VM_IMAGE=Canonical:0001-com-ubuntu-server-focal:20_04-lts-gen2:latest
+  VM_SIZE=Standard_B2ms
+  NSG_NAME=nvflare_nsgs
+  ADMIN_USERNAME=nvflare
+  PASSWORD="NVFl@r3_P@88"$RANDOM"w0rd"
+  DEST_FOLDER=/var/tmp/cloud
+  NIC_NAME=${VM_NAME}VMNic
+  SERVER_NAME={~~server_name~~}
+  FL_PORT=8002
+  ADMIN_PORT=8003
+
+  self_dns=true
+  if [[ "$SERVER_NAME" = *".cloudapp.azure.com"* ]]
+  then
+    DNS_TAG=$(echo $SERVER_NAME | cut -d "." -f 1)
+    LOCATION=$(echo $SERVER_NAME | cut -d "." -f 2)
+    self_dns=false
+  else
+    echo "Warning: ${SERVER_NAME} does not end with .cloudapp.azure.com."
+    echo "The cloud launch process will not create the domain name for you."
+    echo "Please use your own DNS to set the information."
+    LOCATION=westus2
+  fi
+
+  if [ -z ${config_file+x} ]
+  then
+    useDefault=true
+  else
+    useDefault=false
+    . $config_file
+    report_status "$?" "Loading config file"
+  fi
+
+  echo "This script requires az (Azure CLI), sshpass and jq.  Now checking if they are installed."
+
+  check_binary az "Please see https://learn.microsoft.com/en-us/cli/azure/install-azure-cli on how to install it on your system."
+  check_binary sshpass "Please install it first."
+  check_binary jq "Please install it first."
+
+  if [ $useDefault = true ]
+  then
+    while true
+    do
+      prompt VM_IMAGE "Cloud VM image, press ENTER to accept default ${VM_IMAGE}: "
+      prompt VM_SIZE "Cloud VM size, press ENTER to accept default ${VM_SIZE}: "
+      if [ $self_dns = true ]
+      then
+        prompt LOCATION "Cloud location, press ENTER to accept default ${LOCATION}: "        
+        prompt ans "VM image = ${VM_IMAGE}, VM size = ${VM_SIZE}, location = ${LOCATION}, OK? (Y/n) "
+      else
+        prompt ans "VM image = ${VM_IMAGE}, VM size = ${VM_SIZE}, OK? (Y/n) "
+      fi
+      if [[ $ans = "" ]] || [[ $ans =~ ^(y|Y)$ ]]; then break; fi
+    done
+  fi
+
+  echo "If the client requires additional dependencies, please copy the requirements.txt to ${DIR}."
+  prompt ans "Press ENTER when it's done or no additional dependencies. "
+
+  az login
+
+  # Start provisioning
+
+  echo "Creating Resource Group $RESOURCE_GROUP at Location $LOCATION"
+  az group create --output none --name $RESOURCE_GROUP --location $LOCATION
+  report_status "$?" "creating resource group"
+
+  echo "Creating Virtual Machine, will take a few minutes"
+  if [ $self_dns = true ]
+  then
+    az vm create \
+      --output json \
+      --resource-group $RESOURCE_GROUP \
+      --location $LOCATION \
+      --name $VM_NAME \
+      --image $VM_IMAGE \
+      --size $VM_SIZE \
+      --admin-username $ADMIN_USERNAME \
+      --admin-password $PASSWORD \
+      --authentication-type password \
+      --public-ip-address nvflare_server_ip \
+      --public-ip-address-allocation static > /tmp/vm.json
+  else
+    az vm create \
+      --output json \
+      --resource-group $RESOURCE_GROUP \
+      --location $LOCATION \
+      --name $VM_NAME \
+      --image $VM_IMAGE \
+      --size $VM_SIZE \
+      --admin-username $ADMIN_USERNAME \
+      --admin-password $PASSWORD \
+      --authentication-type password \
+      --public-ip-address nvflare_server_ip \
+      --public-ip-address-allocation static \
+      --public-ip-address-dns-name $DNS_TAG > /tmp/vm.json
+  fi
+  report_status "$?" "creating virtual machine"
+
+  IP_ADDRESS=$(jq -r .publicIpAddress /tmp/vm.json)
+  echo "Setting up network related configuration"
+  az network nsg create \
+    --output none \
+    --resource-group $RESOURCE_GROUP \
+    --location $LOCATION \
+    --name $NSG_NAME
+  report_status "$?" "creating network security group"
+
+  az network nsg rule create \
+    --output none \
+    --resource-group $RESOURCE_GROUP \
+    --name SSH \
+    --nsg-name $NSG_NAME \
+    --priority 1000 \
+    --protocol Tcp \
+    --destination-port-ranges 22
+  report_status "$?" "creating network security group rule for SSH"
+
+  az network nsg rule create \
+    --output none \
+    --resource-group $RESOURCE_GROUP \
+    --name FL_PORT \
+    --nsg-name $NSG_NAME \
+    --priority 1001 \
+    --protocol Tcp \
+    --destination-port-ranges $FL_PORT
+  report_status "$?" "creating network security group rule for FL port"
+
+  az network nsg rule create \
+    --output none \
+    --resource-group $RESOURCE_GROUP \
+    --name ADMIN_PORT \
+    --nsg-name $NSG_NAME \
+    --priority 1002 \
+    --protocol Tcp \
+    --destination-port-ranges $ADMIN_PORT
+  report_status "$?" "creating network security group rule for Admin port"
+
+  az network nic update \
+    --output none \
+    --resource-group $RESOURCE_GROUP \
+    --name $NIC_NAME \
+    --network-security-group $NSG_NAME
+  report_status "$?" "updating network interface card"
+
+  echo "Copying files to $VM_NAME"
+  DEST=$ADMIN_USERNAME@${IP_ADDRESS}:$DEST_FOLDER
+  echo "Destination folder is ${DEST}"
+  cd $DIR/.. && sshpass -p $PASSWORD scp -r -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $PWD $DEST
+  report_status "$?" "copying startup kits to VM"
+
+  echo "Installing packages in $VM_NAME, may take a few minutes."
+  az vm run-command invoke \
+    --output json \
+    --resource-group $RESOURCE_GROUP \
+    --command-id RunShellScript \
+    --name $VM_NAME \
+    --scripts \
+    "echo ${DEST_FOLDER} && \
+    wget -q https://bootstrap.pypa.io/get-pip.py && \
+    python3 get-pip.py && \
+    python3 -m pip install --ignore-installed nvflare && \
+    touch ${DEST_FOLDER}/startup/requirements.txt && \
+    python3 -m pip install -r ${DEST_FOLDER}/startup/requirements.txt && \
+    ${DEST_FOLDER}/startup/start.sh && \
+    sleep 20 && \
+    cat ${DEST_FOLDER}/log.txt" > /tmp/vm_create.json
+  report_status "$?" "installing packages"
+
+  echo "System was provisioned"
+  # echo "The VM was created with user: ${ADMIN_USERNAME} and password: ${PASSWORD}"
+
+
+azure_start_cln_sh: |
+  #!/usr/bin/env bash
+  DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
+  function report_status() {
+    status="$1"
+    if [ "${status}" -ne 0 ]
+    then
+      echo "$2 failed"
+      exit "${status}"
+    fi
+  }
+
+  function check_binary() {
+    echo -n "Checking if $1 exists. => "
+    if ! command -v $1 &> /dev/null
+    then
+      echo "not found. $2"
+      exit 1
+    else
+      echo "found"
+    fi
+  }
+
+  function prompt() {
+    local __default="$1"
+    read -p "$2" ans
+    if [[ ! -z "$ans" ]]
+    then
+      eval $__default="'$ans'"
+    fi
+  }
+
+  # parse arguments
+  while [[ $# -gt 0 ]]
+  do
+      key="$1"
+      case $key in
+          --config)
+              config_file=$2
+              shift
+          ;;
+      esac
+      shift
+  done
+
+  RESOURCE_GROUP=nvflare_client_rg
+  VM_NAME=nvflare_client
+  VM_IMAGE=Canonical:0001-com-ubuntu-server-focal:20_04-lts-gen2:latest
+  VM_SIZE=Standard_B2ms
+  NSG_NAME=nvflare_nsgc
+  ADMIN_USERNAME=nvflare
+  PASSWORD="NVFl@r3_P@88"$RANDOM"w0rd"
+  DEST_FOLDER=/var/tmp/cloud
+  LOCATION=westus2
+  NIC_NAME=${VM_NAME}VMNic
+
+  if [ -z ${config_file+x} ]
+  then
+      useDefault=true
+  else
+      useDefault=false
+      . $config_file
+      report_status "$?" "Loading config file"
+  fi
+
+  echo "This script requires az (Azure CLI), sshpass and jq.  Now checking if they are installed."
+
+  check_binary az "Please see https://learn.microsoft.com/en-us/cli/azure/install-azure-cli on how to install it on your system."
+  check_binary sshpass "Please install it first."
+  check_binary jq "Please install it first."
+
+  if [ $useDefault = true ]
+  then
+    while true
+    do
+      prompt LOCATION "Cloud location, press ENTER to accept default ${LOCATION}: "
+      prompt VM_IMAGE "Cloud VM image, press ENTER to accept default ${VM_IMAGE}: "
+      prompt VM_SIZE "Cloud VM size, press ENTER to accept default ${VM_SIZE}: "
+      prompt ans "location = ${LOCATION}, VM image = ${VM_IMAGE}, VM size = ${VM_SIZE}, OK? (Y/n) "
+      if [[ $ans = "" ]] || [[ $ans =~ ^(y|Y)$ ]]; then break; fi
+    done
+  fi
+
+  echo "If the client requires additional dependencies, please copy the requirements.txt to ${DIR}."
+  prompt ans "Press ENTER when it's done or no additional dependencies. "
+
+  az login
+
+  # Start provisioning
+
+  echo "Creating Resource Group $RESOURCE_GROUP at Location $LOCATION"
+  az group create --output none --name $RESOURCE_GROUP --location $LOCATION
+  report_status "$?" "creating resource group"
+
+  echo "Creating Virtual Machine, will take a few minutes"
+  az vm create \
+    --output json \
+    --resource-group $RESOURCE_GROUP \
+    --location $LOCATION \
+    --name $VM_NAME \
+    --image $VM_IMAGE \
+    --size $VM_SIZE \
+    --admin-username $ADMIN_USERNAME \
+    --admin-password $PASSWORD \
+    --authentication-type password > /tmp/vm.json
+  report_status "$?" "creating virtual machine"
+
+  IP_ADDRESS=$(jq -r .publicIpAddress /tmp/vm.json)
+
+  echo "Setting up network related configuration"
+
+  az network nsg create \
+    --output none \
+    --resource-group $RESOURCE_GROUP \
+    --location $LOCATION \
+    --name $NSG_NAME
+  report_status "$?" "creating network security group"
+
+  az network nsg rule create \
+    --output none \
+    --resource-group $RESOURCE_GROUP \
+    --name SSH \
+    --nsg-name $NSG_NAME \
+    --priority 1000 \
+    --protocol Tcp \
+    --destination-port-ranges 22
+  report_status "$?" "creating network security group rule for SSH"
+
+  az network nic update \
+    --output none \
+    --resource-group $RESOURCE_GROUP \
+    --name $NIC_NAME \
+    --network-security-group $NSG_NAME
+  report_status "$?" "updating network interface card"
+
+  echo "Copying files to $VM_NAME"
+  DEST=$ADMIN_USERNAME@$IP_ADDRESS:$DEST_FOLDER
+  echo "Destination folder is ${DEST}"
+  cd $DIR/.. && sshpass -p $PASSWORD scp -r -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $PWD $DEST
+  report_status "$?" "copying startup kits to VM"
+
+  echo "Installing packages in $VM_NAME, may take a few minutes."
+  az vm run-command invoke \
+    --output json \
+    --resource-group $RESOURCE_GROUP \
+    --command-id RunShellScript \
+    --name $VM_NAME \
+    --scripts \
+    "echo ${DEST_FOLDER} && \
+    wget -q https://bootstrap.pypa.io/get-pip.py && \
+    python3 get-pip.py && \
+    python3 -m pip install --ignore-installed nvflare && \
+    touch ${DEST_FOLDER}/startup/requirements.txt && \
+    python3 -m pip install -r ${DEST_FOLDER}/startup/requirements.txt && \
+    ${DEST_FOLDER}/startup/start.sh && \
+    sleep 20 && \
+    cat ${DEST_FOLDER}/log.txt" > /tmp/vm_create.json
+  report_status "$?" "installing packages"
+
+  echo "System was provisioned"
+  # echo "To login to the VM with SSH, use ${ADMIN_USERNAME} : ${PASSWORD}"
+
+azure_start_dsb_sh: |
+  #!/usr/bin/env bash
+
+  function report_status() {
+    status="$1"
+    if [ "${status}" -ne 0 ]
+    then
+      echo "$2 failed"
+      exit "${status}"
+    fi
+  }
+
+  function check_binary() {
+    if ! command -v $1 &> /dev/null
+    then
+      echo $2
+      exit 1
+    else
+      echo "$1 found"
+    fi
+  }
+  
+  # Users are free to change information below.
+  RESOURCE_GROUP=nvflare_dashboard_rg
+  VM_NAME=nvflare_dashboard
+  VM_IMAGE=Canonical:0001-com-ubuntu-server-focal:20_04-lts-gen2:latest
+  VM_SIZE=Standard_B2ms
+  NSG_NAME=nvflare_nsgc
+  ADMIN_USERNAME=nvflare
+  PASSWORD="NVFl@r3_P@88"$RANDOM"w0rd"
+  DEST_FOLDER=/var/tmp/cloud
+  LOCATION=westus2
+
+  # This section is generated by dashboard.  Please don't change it.
+  NIC_NAME=${VM_NAME}VMNic
+
+  echo "This script requires az (Azure CLI), jq and sshpass.  Now checking if they are installed."
+
+  check_binary az "Azure CLI 'az' could not be found.  Please see https://learn.microsoft.com/en-us/cli/azure/install-azure-cli on how to install it on your system."
+  check_binary sshpass "Command 'sshpass' could not be found.  Please install it first."
+  check_binary jq "Command 'jq' could not be found.  Please install it first."
+
+  echo "One initial user will be created when starting dashboard."
+  echo "Please enter the email address for this user."
+  read email
+
+  az login
+  # Start provisioning
+  echo "Creating Resource Group $RESOURCE_GROUP at Location $LOCATION"
+  az group create --output none --name $RESOURCE_GROUP --location $LOCATION
+  report_status "$?" "creating resource group"
+
+  echo "Creating Virtual Machine, will take a few minutes"
+  az vm create \
+    --output json \
+    --resource-group $RESOURCE_GROUP \
+    --location $LOCATION \
+    --name $VM_NAME \
+    --image $VM_IMAGE \
+    --size $VM_SIZE \
+    --admin-username $ADMIN_USERNAME \
+    --admin-password $PASSWORD \
+    --authentication-type password > /tmp/vm.json
+  report_status "$?" "creating virtual machine"
+
+  echo "The VM was created with user: ${ADMIN_USERNAME} and password: ${PASSWORD}"
+
+  IP_ADDRESS=$(jq -r .publicIpAddress /tmp/vm.json)
+  report_status "$?" "extracting ip address"
+
+  echo "Setting up network related configuration"
+  az network nsg create \
+    --output none \
+    --resource-group $RESOURCE_GROUP \
+    --location $LOCATION \
+    --name $NSG_NAME
+  report_status "$?" "creating network security group"
+
+  az network nsg rule create \
+    --output none \
+    --resource-group $RESOURCE_GROUP \
+    --name SSH \
+    --nsg-name $NSG_NAME \
+    --priority 1000 \
+    --protocol Tcp \
+    --destination-port-ranges 22
+  report_status "$?" "creating network security group rule for SSH"
+
+  az network nsg rule create \
+    --output none \
+    --resource-group $RESOURCE_GROUP \
+    --name HTTPS \
+    --nsg-name $NSG_NAME \
+    --priority 1001 \
+    --protocol Tcp \
+    --destination-port-ranges 443
+  report_status "$?" "creating network security group rule for HTTPS"
+
+  az network nic update \
+    --output none \
+    --resource-group $RESOURCE_GROUP \
+    --name $NIC_NAME \
+    --network-security-group $NSG_NAME
+  report_status "$?" "updating network interface card"
+
+  echo "Installing docker engine in $VM_NAME, may take a few minutes."
+  az vm run-command invoke \
+    --output json \
+    --resource-group $RESOURCE_GROUP \
+    --command-id RunShellScript \
+    --name $VM_NAME \
+    --scripts \
+    "sudo apt-get update && \
+    sudo DEBIAN_FRONTEND=noninteractive apt-get install -y ca-certificates curl gnupg lsb-release && \
+    sudo mkdir -p /etc/apt/keyrings && \
+    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg && \
+    echo \
+    \"deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
+    $(lsb_release -cs) stable\" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null && \
+    sudo apt-get update && \
+    sudo DEBIAN_FRONTEND=noninteractive apt-get install -y docker-ce docker-ce-cli containerd.io && \
+    sudo usermod -aG docker $ADMIN_USERNAME" > /tmp/docker_engine.json
+  report_status "$?" "installing docker engine"
+    
+  DEST_FOLDER=/home/${ADMIN_USERNAME}
+  echo "Installing nvflare in $VM_NAME, may take a few minutes."
+  az vm run-command invoke \
+    --output json \
+    --resource-group $RESOURCE_GROUP \
+    --command-id RunShellScript \
+    --name $VM_NAME \
+    --scripts \
+    "echo ${DEST_FOLDER} && \
+    wget -q https://bootstrap.pypa.io/get-pip.py && \
+    python3 get-pip.py && \
+    python3 -m pip install --ignore-installed nvflare && \
+    mkdir -p /var/tmp/nvflare/dashboard/cert && \
+    chown -R $ADMIN_USERNAME /var/tmp/nvflare && \
+    ls -lR /var/tmp/nvflare && \
+    mkdir -p ${DEST_FOLDER}/cert && \
+    chown -R ${ADMIN_USERNAME} ${DEST_FOLDER}" > /tmp/nvflare.json && \
+  report_status "$?" "installing nvflare"
+
+  echo "Checking if certificate (web.crt) and private key (web.key) are available"
+  if [[ -f "web.crt" && -f "web.key" ]]; then
+    DEST=$ADMIN_USERNAME@$IP_ADDRESS:${DEST_FOLDER}/cert
+    echo "Destination folder is ${DEST}"
+    sshpass -p $PASSWORD scp -o StrictHostKeyChecking=no web.{crt,key} $DEST
+    report_status "$?" "copying cert/key to VM ${DEST} folder"
+  else
+    echo "No web.crt and web.key found"
+  fi
+
+  echo "Starting dashboard"
+  az vm run-command invoke \
+    --output json \
+    --resource-group $RESOURCE_GROUP \
+    --command-id RunShellScript \
+    --name $VM_NAME \
+    --scripts \
+    "cd ${DEST_FOLDER} && \
+     echo ${email} | nvflare dashboard --start -f ${DEST_FOLDER}" > /tmp/dashboard.json
+
+  credential=$(jq -r .value[0].message /tmp/dashboard.json | grep "Project admin")
+  
+  echo "Dashboard: ${credential}, running at IP adress ${IP_ADDRESS}"
+  echo "To stop it, run az group delete -n ${RESOURCE_GROUP}"
